news_sites:
  rancaguino:
    url: https://www.elrancaguino.cl
    queries:
      homepage_article_links: ".jeg_postblock_content a"
      article_title: ".entry-header h1"
      article_body: ".entry-content p"

  latercera:
    url: https://www.latercera.com/
    queries:
      homepage_article_links: ".headline a"
      article_title: ".titulares h1 div"
      article_body: ".single-content p"
      
  emol:
    url: https://www.emol.com/
    queries:
      homepage_article_links: ".divico_txt a"
      article_title: ".cuDetalle_cuTitular_contNoticia h1"
      article_body: ".EmolText div"
      